### ISSUE TITLE
Do we need "Comments" section for blog?

### ISSUE THREAD

**Issue by ibelem** [webmachinelearning/webmachinelearning.github.io#35]
@anssiko Just found https://github.com/giscus/giscus is a great comment system powered by GitHub Discussions, please let me know if we need it.

Demo @ page footer of https://pwadev.io/blog/try-out-webnn-api-early-using-webnn-polyfill

**Comment by anssiko** [comment]
Can we enable just reactions via giscus?

Comments may require manual moderation to avoid spam and inappropriate comments. I think a fully automated NLP-powered solution for moderation would be out of scope for this feature :-)

**Comment by ibelem** [comment]
Thanks @anssiko , got your concern and seems like still lack of the moderation feature via giscus, close this issue. :)
