### ISSUE TITLE
Add/report WebNN implementation status support on MacOS ( via CoreML/ML Compute)..

### ISSUE THREAD

**Issue by oscarbg** [webmachinelearning/webmachinelearning.github.io#70]
Seems chromium webnn implementation is adding support for accelerated webNN on MacOS via CoreML and/or ML Compute Apple frameworks.. can update implementation status page (https://webmachinelearning.github.io/webnn-status/) to report current MacOS GPU/NPU support?

**Comment by ibelem** [comment]
Thanks @oscarbg for the great feedback, we do have this plan. :)

**Comment by ibelem** [comment]
@oscarbg @christianliebel The WebNN Core ML implementation status has been updated @ https://webmachinelearning.github.io/webnn-status/ , PTAL.

@anssiko Could you please help to close this issue, thanks!

**Comment by anssiko** [comment]
Fixed by https://github.com/webmachinelearning/webmachinelearning.github.io/pull/80 🥳
